extends Node

const Move			 = 	preload("res://ecs/Systems/Move.gd")
const Input			 =  preload("res://ecs/Systems/Input.gd")
const Animation		 =  preload("res://ecs/Systems/Animation.gd")
const Collision		 =  preload("res://ecs/Systems/Collision.gd")
const Patrol 		 =  preload("res://ecs/Systems/Patrol.gd")
const Missile 		 =  preload("res://ecs/Systems/Missile.gd")
const Hud			 =  preload("res://ecs/Systems/Hud.gd")
const Bounce		 =  preload("res://ecs/Systems/Bounce_collision.gd")
const Shop			 =  preload("res://ecs/Systems/Shop.gd")
const Bullet		 =   preload("res://ecs/Systems/Bullet.gd")
const Answer		 =   preload("res://ecs/Systems/Answer_system.gd")
const EmitPArticules =   preload("res://ecs/Systems/Emit_particules.gd")
const Endfight		 =   preload("res://ecs/Systems/End_fight.gd")
const UpsideDown	 =   preload("res://ecs/Systems/Move_UpsideDown.gd")
const Critic			 =   preload("res://ecs/Systems/Critic.gd")
